<a href="https://colab.research.google.com/github/dwelle511/2026BDA/blob/main/BDA_Day03_except3dim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy 다차원 배열, 과학용 컴퓨팅 패키지, 수치 계산 신속,
#nd= multi dimension,동일한 크기 자료형 항목 자료형 으로 구성, numpy.ndarray(size,dtype)
#ndarry: numpy다로는 대표적인 자료형, numpy.ndarray(size,dtype), 값은 임의의 값
import numpy as np

a=np.ndarray((2,3))
a

array([[4.85710457e-316, 0.00000000e+000, 0.00000000e+000],
       [1.00243081e-310, 1.07034138e-296, 1.99260935e-311]])

## numpy
- 다차원 배열= n-dimensional arrays : ndarray , 다차원 배열, 동일한 데이터 타입의 요소로 이루어진 다차원 배열
- 브로드 캐스킹 : 다른 모양, 확장 가능 배열 간에 연산이 가능하도롣 기능 제공, when array 크기 or 차원 다르면 => 자동 배열 확장
- 유니버셜 함수 : array에서 요소별로 작동하여 배열을 출력으로 생성
- 선형 대수 : 행렬 곱셈, 행렬 분해, 역행렬 등 선형 대수 연산 가능
- 난수 생성 : 무작위 수 생성


In [2]:
a=np.ndarray((3,2), dtype=int) #numpy.ndarray(size,dtype): 값은 임의의 값
a

array([[          98308891,                  0],
       [                 0,     20289425506304],
       [179018085187977216,      4033086227836]])

In [3]:
#기본 자료형 @@@@
#bool, int, float, complex,int8,int16,int32, uint8=부호 없는 8bit정수 , float16=16bit 부동 소수점
#complex128= 128bit 복소수
#
#@@@@
#ndarray.shape= 배열의 차원을 나타내는 튜플, 각 차언의 크기 표현
#.ndim= array 차원 수 , .size=array 요소 수
#.dtype=array 데이터 형식, .itemsize=array 각 요소의 크기(byte), nbytes=array 전체 크기(byte)
#ndarray.data= array 요소를 실제로 표함하고 있는 버퍼의 시작 위치

In [4]:
#내장 함수 array()
# ndarray.shape : 배열의 차원을 나타내는 튜플, 각 차원의 크기 표현
# ndarray.ndim : 배열의 차원 수
# ndarray.size: 배열의 총 요수 수
# ndarray.dtype: 배열 요소의 데이터 형식
# ndarray.itemsize: 배열의 각 요소의 크기(바이트)
# ndarray.nbytes:배열의 전체 크기(바이트)
# ndarray.data:배열 요소를 실제로 포함하고 있는 버퍼의 시작 위치

#1차원 (3,) 로 나옴
#

In [6]:
a=np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [7]:
print(a.shape)# 차열의 차원을 나타내는 튜플, 각 차원의 크기
print(a.ndim) #배열의 차원수
print(a.dtype) #배열의 데이터 형식

(3,)
1
int64


In [ ]:
#ndarray(다차원 배열) 특징, 하나라도 문자열이면 모든 항목이 동일하게 유니코드 문자열 자료형인 '<u32'지정

#ndarray.shape : 배열의 차원을 나타내는 튜플, 각 차원의 크기를 표현
#ndarray.ndim: 배열의 차원 수
#ndarray.size : 배열의 총 요소 수
#ndarray.dtype : 배열의 요소의 데이터 형식
#ndarray.itemsize : 배열의 각 요소의 크기 ,byte
#ndarray.nbytes : 배열의 전체 크기 ,byte
#ndarray.data : 배열 요소를 실제로 포함하고 있는 버퍼의 시작 위치

In [8]:
sanga=np.array([1,2])
print(sanga.size) #배열의 총 요소 수
print(sanga.itemsize) #배열의 각 요소의 크기
print(sanga.nbytes) #배열의 전체 크기
print(sanga.data) #배열의요소를 실제로 포함하고 있는 버퍼의 시작 위치

2
8
16


In [ ]:
#ndarray특징 : 모든 요소가 단일한 자료형으로 구성
#하나라도 문자열인면 모든 항목이 동일하게 유니코드 문자열 자료형인 'u32'로 지정
#numpy 자료형은 데이터의 저장 방식과 크기르 지정하는데 사용, 배열 요손는 이러한 자료형 중 하나만을 가짐

In [9]:
np.array([1,'py',3.14]) #동일 자료형이여햐 하므로 문자열이됨


array(['1', 'py', '3.14'], dtype='<U32')

In [11]:
import numpy as np
unicode_array=np.array(['abc'*2,'def','ghi'])
unicode_array

array(['abcabc', 'def', 'ghi'], dtype='<U6')

## 3.2내장함수 arange() linspace()

In [ ]:
#numpy.arange([start=0,]stop,[step=1,dtype=None,*,like=None])
#주어진 간격내의 균등한 간격의 값을 반환하며, 다양한 수의 위치 인수를 사용하여 호출하고, 정수 인수의 경우
#함수는 파이선 내장함수 range()와 거의 동일하지만 range인스턴스가 아닌 ndarray를 반환

In [12]:
#numpy.arange()

import numpy as np
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(1,7,2.3))
#py, range(){{정수}}만됨 vs numpy arange()는 '실수'도된

[0 1 2]
[3 4 5 6]
[1.  3.3 5.6]


In [13]:
import numpy as np
print(np.arange(3.0))
print(np.arange(3.3,7.4))
print(np.arange(1.0,7.0,2.3))#step크기 지정

[0. 1. 2.]
[3.3 4.3 5.3 6.3 7.3]
[1.  3.3 5.6]


In [14]:
#reshape() 배열의 모양을 바꾸는
#

import numpy as np

a=np.arange(12).reshape(3,4) #.reshape(n,m) 2개라 2차원
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
np.reshape(a,(2,6)) #12개

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
#np.reshape(a,(3,5)) #size원소 개수 다름, 15개 , because) a.size=> 12
# error )cannot reshape array of size 12 into shape (3,5)

In [16]:
#linspace(start,stop,num) @@
#일정한 간격의 값으로 배열 생성
#동일한 길이의 하위 간격으로 분할하는 수가 나열된 1차원 배열을 반환
#arrays with regularly-spaced
#전체 구간은 [시작, 끝]으로 기본적인 양쪽을 모두 포함, 일정한 간격을 구성하는 값인 배열의 수를 매개변수 num에 지정하여 기본값은 50
#np.linspace(start,stop,num) #num부분에 이제 step=2 즉 원소개수 2개라는거다
linsp=np.linspace(0,10,2)
linsp

array([ 0., 10.])

In [ ]:
#start=포함, stop=포함, num=성성 점의 개수=step=(stop-start)/(num-1)\
stepNum=(10-0)/(2-1)
print("num구간의 개수아닌 크기",stepNum)

#np.arange= step크기 지정 vs np.linspace=점 개수 지정, 구간 정확힌 n등분시 유리함

num구간의 개수아닌 크기 10.0


In [ ]:
#linspace(start,stop,num)
#numpy.linspace(start,stop,num=50,endpoint=True,restep=False,dtype=None,axis=0)

#지정된 간격에 걸쳐 균등한 간격의 숫자를 반환
#endpoint: bool,optional, 끝점은 제외 될 수 있음=True, False=제외
# retstop=True: (samples,step)반환= step 샘풀 수 사이 간격= step크기, false=samples만 반환

In [ ]:
#지정된 간격에 걸쳐 균등한
#89P.
np.linspace(2.0,3.0) #50개 자동

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
np.linspace(2.0,3.0,retstep=True) #
#바닥에 무엇? retstep=True 면 반환:(samples,step) 스텝은 샘플 수 사이의 간격

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [17]:
#step size
print((3-2)/(50-1))

0.02040816326530612


In [18]:
np.linspace(2.0,3.0,3,endpoint=False,retstep=True) #끝수 포함 제외


(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [19]:
np.linspace(2.0,3.0,3,endpoint=True,retstep=True) #끝수 포함


(array([2. , 2.5, 3. ]), np.float64(0.5))

In [20]:
np.linspace(2,3,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

#3.3 내장 함수 zeros() ,ones(),empty()

In [ ]:
#내장함수 np.zeros()
#주어지는 shape형태로 0.0이 채워진

import numpy as np
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
b=np.zeros((2,1)) #.zeros((행개수, 열))
b

array([[0.],
       [0.]])

In [ ]:
b=np.zeros((2,3)) #.zeros((행개수, 열))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#원소가 모두 1.0인 배열을 생성 .one()
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#numpy.eye() 대각선 원소가 모두 1인 2차원 배열을 반환하는 함수
#대각행렬 만들때, eye(m,n,k),m row, n col, k=+n으로 양수, k=-n음수

np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
#numpy.full
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full([2,3],(1,2)) #error =>

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [ ]:
#np.full

np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.arange(4).reshape(4,1) #이거인데 full(row, col)로 오른쪽 으로 복사한게 다음 거

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
#원래 arange하면 1차원 배열 생성, reshape(row,col) 4row,1col생성
np.full([4,3],fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
#지정한 모양의 배열을 생성하는 numpy.empty(shape)
#값은 메모리 값 지정
# 원소 값 예측 할 수 없음
np.empty(3)

array([1., 1., 1.])

In [ ]:
np.empty([2,2])

array([[0.4, 2.4],
       [4.4, 6.4]])

In [ ]:
np.empty([2,3],dtype=int)

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
#원소값이 0인 주어진 형태의 배열을 생성한느 zeros_like(a)
#인지안 a형태의 배열로 원소 값은 모두 0인 배열을 반환
import numpy as np

a=np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
#내장함수 np.zeros()
#주어지는 shape 형태로 0.0이 채워진 ndarray를 밙환하는 함수

import numpy as np
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
b=np.zeros((2,1))
b

array([[0.],
       [0.]])

In [ ]:
#원소가 모두 1.0인 배열을 생성하는 ones()
#zeros()처럼 모두 실수 1.0인 배열을 반환한는 함수
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#numpy.eye()
#데긱산 원소가 모두 1인 2차원 배열을 반환한느 함수
#eye(m,n,k)호출 , m행과 n열의 2차원 배열을 반환, k=+n양수 오른쪽 위쪽 방향으로 n번 이동된 위치의 대각선이 1이 저장
# k=-n 음수, 왼쪽 아래쪽 방향으로 n번 이동된 위치의 대각선이 1이 저장

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a=np.eye(3,4,+2)
a

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
b=np.eye(3,4,-1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
#numpy.full(shape,fill_value) : fullvaluefh로 shape 모양의 배열ㅇ르 반환
#cf)값 fill_value가 없으면 오류 발생

np.full([2,3],10)


array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2,3],(1,22,3))

array([[ 1, 22,  3],
       [ 1, 22,  3]])

In [ ]:
np.full([2,3],6)
#error )could not broadcast input array from shape (2,) into shape (2,3)
#=> full(n,m) 에서 n개의 .size에 맞춰야 한다 m은

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4,3],fill_value=np.arange(4).reshape(4,1)) #reshape 는 왜??

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
#원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like(a)

import numpy as np
a=np.arange(1,17,2).reshape(2,4)
a

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [ ]:
0#원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()
#zeros()처럼 모두 1인 배열을 반환하는 함수
np.ones_like(a) #뭐랄까 a.size에 따라 만들어 지는것으로 보임

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#원소값이 주어진 값이며 주어진 형태의 배열을 생성하는 full_like()
#주어진 값으로 배열을 반환한느 함수
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

## 3.4 배열 연산

In [ ]:
#배열 스칼라와 연산
import numpy as np
a=np.arange(3)
a
print(a/2)

[0.  0.5 1. ]


In [ ]:
#배열과 배열의 연산
a=np.arange(1,7).reshape(2,3)
b=np.full_like(a,[1,2,3])

print(b)

[[1 2 3]
 [1 2 3]]


In [ ]:
#복합 대입 연산자도 지원
a=np.arange(4)

b=np.arange(0.4,4,1)

# a+=b =>error) nnot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
b+=a #a는 int b는 float더 커서#
b

array([0.4, 2.4, 4.4, 6.4])

In [ ]:
#2차원 배열이 곱 연산자 = @
#(3,2) @(2,1)
x=np.arange(1,7).reshape(2,3)
x
y=np.arange(1,4).reshape(3,1)
y
print(x @ y)

[[14]
 [32]]


In [ ]:
#다양한 배열의 곱 연산자
a=np.full((2,3),[1,2,3])
b=np.full((3,2),[2,1])

a@b

array([[12,  6],
       [12,  6]])

In [ ]:
a.dot(b)
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [ ]:
import numpy as np
print(np.matmul(a,b))
print(np.matmul(b,a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


In [ ]:
#배열 함수 @@
a=np.array([[10,20],[5,7],[1,2]])
a

array([[10, 20],
       [ 5,  7],
       [ 1,  2]])

In [ ]:
a.sum() #모든 원소의 합

np.int64(45)

In [ ]:
a.sum(axis=1) #열 합 배열

array([30, 12,  3])

In [ ]:
import numpy as np
 #@@@@ 열더행더 !!
print(np.sum(a))
print(np.sum(a,axis=0)) #열 더한거
print(np.sum(a,axis=1)) # 행으로 더한거


45
[16 29]
[30 12  3]


In [24]:
#배열 함수 a.cumsum() d: 원소를 누적한 1차원 배열
#cumulate : 쌓아 올리다,누적하다
a=np.array([[3,5,8],[1,2,3]])
a
print(a.cumsum(),"/n")
print(a.cumsum(axis=0)) #각 행을 따라 세로로 합산
print(a.cumsum(axis=1)) #각 행에 대한 모든 열에서 동작
#열을 따라 가로로 합산

[ 3  8 16 17 19 22] /n
[[ 3  5  8]
 [ 4  7 11]]
[[ 3  8 16]
 [ 1  3  6]]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b.cumsum(axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [ ]:
#범용 함수
# 다양한 수학 및 통계적 연산을 수행할 수있도와줌, universal function, 배열에서 요소별로 작동하여 배열을 출력으로 생성
aa=np.sin([np.pi/2,np.pi/2*4],dtype=float) #? 두개의 배열의 크기가 다르면 브로드 캐스팅 될까?
aa

array([ 1.0000000e+00, -2.4492936e-16])

In [ ]:
bb=np.cos([np.pi/2*0,np.pi/2*1,np.pi/2*4]) #?np.pi/2*1는 결과가 이상하넫 너무 큰데
bb

array([1.000000e+00, 6.123234e-17, 1.000000e+00])

In [ ]:
cc=np.exp([1,2,3]) #로그 함수
cc

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
dd=np.log([1,np.e,np.e**2]) #지수함수
dd

array([0., 1., 2.])

In [ ]:
#다양한 이항 연산 범용 함수,
import numpy as np
a=np.array([1,4,9])
a

array([1, 4, 9])

In [ ]:
b=np.full_like(a,2)
b

array([2, 2, 2])

In [ ]:
print(np.add(a,b))
print(np.divide(a,b))
print(np.power(a,b))

[ 3  6 11]
[0.5 2.  4.5]
[ 1 16 81]


## 3.5배열 슬라이싱과 형태 수정 @@@@

In [25]:
#1차원 배열의 첨자와 슬라이싱
#a[i] 첨자, a[m:n] , a[m:n:s] 슬라이싱
import numpy as np
a=np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-1])
print(a[1:4])
print(a[-5:-1])
print(a[8:2:-1])
print(a[-1:-7:-1])

9
81
[1 4 9]
[25 36 49 64]
[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [ ]:
#역순 대입
a[::-2]


array([81, 49, 25,  9,  1])

In [27]:
#
a[2:5]=-100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [29]:
a[2:5]=[-5,-5,-5] #대입될 원소의 수 맞춰주기
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [ ]:
#arange vs DataFrame 출력 양상이 다른듯?

In [ ]:
#array 와 arange차이 ndarray?

In [30]:
#2차원 배열 첨자와슬라이싱
#행 잠조 x[row] x[row,] x[row,:] 모두 동일!

a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
#@@@
print(a[-2])

[18 19 20 21 22 23]


In [36]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [37]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [38]:
a[-2,:]

array([18, 19, 20, 21, 22, 23])

In [42]:
#2차원 배열의 첨자와 슬라이싱
#행반환 : x[row],x[row],x[row,:]
#열반환 : x[:,col] ,error ) x[,col] :콜른 넣기!
#원소 반환 : x[row,col]
a=np.arange(30).reshape(5,6)
print(a)
print(a[:,1:3])


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]]


In [43]:
#2차원 배열 첨자와 슬라이싱
a[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [44]:
a[:,::2] #해석 : 행열 다나오는데 열방향으로 2개씩 출력

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [47]:
a[2,4]

np.int64(16)

In [48]:
a[2][4]

np.int64(16)

In [49]:
a[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [45]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [46]:
a[:,1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [50]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [52]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
a[::-1,::-1] #행과 열 모두 역순으로 바꿈

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [54]:
a[:-1,:-1] #마지막 행과 열을 제거한 배열

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [57]:
#3차원 배열 , (3,3,3) 3행 3열의 2차원 배열 3개 / (3,) (3,3) (3,3,3)
#3차원 배열 (2,3,4) 3행 4열인 2차원 배열 2개로
a=np.arange(24).reshape(2,3,4) #@@@
a


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#3개축 0축 =(나,etc,etc) 나[0]번째 덩어리임 1축 =각 행  2축=각 열

In [ ]:
#3차원 배열의 다양한 참조
# a[1] axis=0 첨자 1
# a[:,1] axis=0
#a[:,1,1] axis=0인 모든 배열, 위치 (1,1)
# a[:,:,1]
#a[...1] 해당되는 축이 모두:것을 의미= 동일함 a[:,:,1]
#a[1,...,1] axis=0의 첨자 1 , axis=2의 첨자 1인 (3,)모양 1차원 배열이 반환
#a[0,...]

In [58]:
#@@@@

a=np.arange(24).reshape(2,3,4) #@@@
a[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
#1차원 배열로 만드는 ndarray.ravel()
#행렬인 a에서 a.ravel()의 반환 값은 (a.size,)모양의 1차원 배열
a=np.arange(12).reshape(2,3,2)
print(a,"/n")
b=a.ravel()
print(b) #a.size=12 이다

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] /n
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [62]:
#np.transpose(a) a.transpose(),aT @@@ 함수 호출, 전치 행렬, 행과 열이 바뀜,(2,3)->(3,2)
#2차원 a.T는 쉬운데 3차원은 복잡
import numpy as np
a=np.arange(1,7).reshape(2,3)
print(a)


print(np.transpose(a))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [64]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#3차원 배열 전치행렬 , (3,2,2)-> (2,2,3) ex(i,j,k)->(l,j.i) j는 위치가 그대로
# 전치 행렬 방법 6갸 존쟈 ㅋㅋㅋㅋㅋ, #49~59페이지 시험 제외

In [66]:
#얕은 복사 와 뷰
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
b=a
b is a

True

In [68]:
print(id(a))
print(id(b))

133434968456912
133434968456912


In [69]:
print(a.base)
print(b.base)

None
None


In [70]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [71]:
c=a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [72]:
print(id(a))
print(id(c))

133434968456912
133434968454032


In [73]:
print(c.base)

None


In [75]:
v=a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [76]:
print(id(a))
print(id(v))


133434968456912
133434968453744


In [77]:
v[0,1]=200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [78]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

## 3.6 브로드캐스팅

In [ ]:
#broadcasting: 산술 연산 ㅅ ,작은 배열은 연산이 호환되는 모양이되도록 전파
a=np.array([3,4,5])
b=np.array([8,7,6])
a+b

array([11, 11, 11])

In [ ]:
a=np.array([3,4,5])
b=np.array([8,7,6,6]) #error => operands could not be broadcast together with shapes (3,) (4,)
#두 배열 크기 달라 안됨
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [80]:
#하나의 배열 이 1차원으로 다른 배열 열수 와 같은 구조의 브로드캐스팅

#(3,3)*(3,) or (1,3) 아래로 확장
#
from numpy import  arange
x=arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
y=arange(-1,2) #linspace 50=num
y

array([-1,  0,  1])

In [83]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [84]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [86]:
#하나의 배열이 2차원으로 다른 배열 행수와 같은 구조의 브로드 캐스팅
#row-wise, normalization
from numpy import arange
x=arange(1,10).reshape(3,3)

y=arange(3,10,3).reshape(3,1)

np.set_printoptions(precision=2) #소수점 이하 자릿수를 2자리로 설정,2차원 배열

print(x)
print(y)
print(x/y)
print(x-y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]
[[0.33 0.67 1.  ]
 [0.67 0.83 1.  ]
 [0.78 0.89 1.  ]]
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


In [91]:
from numpy import arange
x=arange(0,10,3).reshape(4,1)
print(x)
y=arange(1,3)
print(y)
print(x*y)
print(x+y)

[[0]
 [3]
 [6]
 [9]]
[1 2]
[[ 0  0]
 [ 3  6]
 [ 6 12]
 [ 9 18]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [90]:
#행 또는 열이 1인 두 배열의 브로드 캐스팅
from numpy import arange
x=arange(1,4)
print(x)
y=arange(1,4).reshape(3,1)
print(y)
print(x*y)
print(x/y)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1.   2.   3.  ]
 [0.5  1.   1.5 ]
 [0.33 0.67 1.  ]]


In [93]:
#상수 np.newaxis 활용한 배열 차원의 확장 =증가, 배열 x:(4,)인 1차원 배열
#x[None,:]또는 x[np.newaxis:], none 이 있는 축인 행이 추가, 모양 (1,4)의 2차원 배열의 보기 (view)
#가 반환, 즉 1차원에서 행이 추가디어 2차원으로 차원 증가
import numpy as np
from numpy import array

x=array([0,10,20,30])
print(x)
print(np.newaxis is None)
a=x[None,:] #추가된 차원이 1이됨, 모양이 (4,)에서 (1,4)됨
a #차수를 증강

[ 0 10 20 30]
True


array([[ 0, 10, 20, 30]])

In [94]:
a=x[np.newaxis,:]
a

array([[ 0, 10, 20, 30]])

In [95]:
#연산 a+b수행, 배열 a는 열이 1이며 배열 b는 행이 1
a=x[:,np.newaxis] #추가 차원이 1이됨, 모양이(4,)에서 (4,1) 됨
a

array([[ 0],
       [10],
       [20],
       [30]])

In [97]:
a.shape

(4, 1)

In [99]:
#연산 a+b수행, 배열 a는 열이 1이며 배열b는 행이 1
a=x[:,np.newaxis]
b=array([1,2,3])

print(a+b)
print(a*b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


## 3.7 고급 색인

In [105]:
#1차원 배열 색인, 1차원 배열 x, x[i] 첨자 i인 원소 참조, 시퀸스인 첨자라면 여러 언소로 구성된 배열 반환
#x[[i,j,k,...]]: 정수 배열 or list 인텍싱, 배열에서 여러 첨자인 원소 선택, 정수 배열 또느 리스트 반환값도 배열
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
import numpy as np
print(x[1])
print(x[:5])
print(x[[2]])
print(x[[2,3]]) #결과는 1차원 배열
print(x[[2,3,5,8]]) #결과는 1차원 배열
print(x[np.array([5,3,-4,8])]) #결과는 1차원 배열
#시퀀스가 첨자라면 여러 원소로구성된 배열 반환

1
[0 1 2 3 4]
[2]
[2 3]
[2 3 5 8]
[5 3 6 8]


In [108]:
#2차원 백열의 색인
x=np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [111]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [112]:
x[0,1]

np.int64(1)

In [109]:
int(x[0,1])

1

In [113]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[,2:8] #:콜론 뺌면 안됨, 3차원이면 가능하지 않나

SyntaxError: invalid syntax (1821174162.py, line 1)

In [ ]:
x[...,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[[0],[1]] #위에 거랑 다른데 어래이이다,행축 열축 해당하는 배열을 만든것

array([1])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[[0,1]] #행번호의 모임

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[[1,3,5]]
#x[[1,3,5],:]
#행번호의 모임 => 고급 색인, 안에 리스트형시그올 써서
#

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[[1,3],[2,2]]

array([10, 26])

In [ ]:
x[[1,3],[2]]

array([10, 26])

In [115]:
#
from numpy import arange
x=arange(56).reshape(7,8)
print(x)
x[0]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


array([0, 1, 2, 3, 4, 5, 6, 7])

In [127]:
print(x[0])
print(x[0,1])
print(x[:2:8])
print(x[[0],[1]]) #리턴은 배열
print(x[[0,1]],"<br>") #행 목록의 2차원 배열 반환
print(x[:,[5,4]]) #열 목록의 2차원 배열 반환
print(x[[1,3]],"same")
print(x[[1,3],:]) #동일


[0 1 2 3 4 5 6 7]
1
[[0 1 2 3 4 5 6 7]]
[1]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]] <br>
[[ 5  4]
 [13 12]
 [21 20]
 [29 28]
 [37 36]
 [45 44]
 [53 52]]
[[ 8  9 10 11 12 13 14 15]
 [24 25 26 27 28 29 30 31]] same
[[ 8  9 10 11 12 13 14 15]
 [24 25 26 27 28 29 30 31]]


In [132]:
#행과 열 참조 매핑 :  x[[1,3],[2,2]] 첨자 [1,2] 와 [3,2]
#원소 x[1,2],x[3,2]로 구성된 배열 반환
#x[[0,2,4],[1]]
# x[[0,2,4],1]
from numpy import arange
x=arange(56).reshape(7,8)
print(x)
print(x[[1,3],[2,2]]) #첨자 [1,2]과 [3,2]에 해당하는 10과 26
print(x[[1,3],[2]]) #동일 , [2]브로드캐스팅으로
print(x[[1,3],2]) #1,3행의 2열


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]
[10 26]
[10 26]
[10 26]


In [134]:
x[np.array([0,2,4]),1]
#1축의 1이 브로드
#x[0,1] x[2,1] x[4,1]의 참조값으로 구성된 1차원 배열

array([ 1, 17, 33])

In [137]:
print(x[0,1])
print(x[2,1])
print(x[4,2])


1
17
34


In [138]:
x[array([0,2,4]),:2]
#행 0,2,4에서 열 0,1로 구성된 2차원 배열 반환

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
#슬라이싱
x[[0,2,4],:1]

array([[ 0],
       [16],
       [32]])

In [ ]:
#기본 색인
from numpy import arange
a=arange(40).reshape(5,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [ ]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
#고급 색인 방법
  # 색인 결과 배열을 다시 색인
from numpy import arange
a=arange(40).reshape(5,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [ ]:
a[arange(2,4)][:,[1,0]] #결과를 다시 색인, 즉 앞결과에서
#1열과 0열을 선택

array([[17, 16],
       [25, 24]])

In [ ]:
a[arange(2,4)][:,[1,1,0]] #

array([[17, 17, 16],
       [25, 25, 24]])

In [ ]:
a[arange(2,5)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [ ]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[arange(2,5)][:,arange(-1,-8,-1)]
#행 2에서 4열까지의 결과에서 열 -1에서 -7까지 선택

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [ ]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[[2,3,4]][:,[-1,-2,-3,-4,-5,-6,-7]]


array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [ ]:
a[np.arange(2,5)][np.arange(-1,-8)]

array([], shape=(0, 8), dtype=int64)

In [ ]:
a[np.arange(2,5)][:,np.arange(-1,-8,-1)] #위에거가 안된=ㅁ

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])