<a href="https://colab.research.google.com/github/dwelle511/2026BDA/blob/main/BDA_Day04_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4.1 배열 결합

In [ ]:
#@@ 배열결합 :8가지!!!!

In [ ]:
#numpy.vstack()
#numpy.hstack()
#numpy.column_stack()
#numpy.row_stack()
#numpy.concatenate()
#numpy.c_[]
#numpy.r_[]
#numpy.matrix()

In [1]:
#numpy.vstack() 배열을 수직로 결합, 세로로, 인자는 튜플
#첫 인자는 튜플 자료형으로(or list), 이 배열들은 0축(?)을 제외한 모양이 동일
import numpy as np

a=np.arange(6).reshape(3,2)
print(a)

b=np.arange(6,12).reshape(3,2)
print(b)

np.vstack((a,b)) #2d->2d

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [2]:
#numpy.vstack([x,y])
#인지인 배열이 1차원이면 길이가 같아야 수직으로 합칠 수 있다

x=np.array([1,2,3])
y=np.array([4,5,6])

np.vstack((x,y))

# 1d-> 2d

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
#numpy.hstack()
#1d: 수평으로 결합, 1d->1d
#2d: row 같아야함, 2d->2d
#nd : 두 번째 축을 제외하고 동일한 모양을 가져야함

import numpy as np

a=np.arange(6).reshape(3,2)
a
b=np.arange(6,12).reshape(3,2)
b
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [6]:
np.hstack((np.arange(3),np.arange(10,15))) #dimentison !!d->1d

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [ ]:
#np.column_stack(a,b)
#2차원 배열 a,b를 수평으로 열(column wise)로 결합

# 1차원 배열 a,b: 1d->2d ; 배열 a,b를 먼저 축1로 확장한 이후, 열로 쌓아 만든 2차원 배열을 반환
# 2차원 배열 a,b : 2d->2d: np.hstack((a,b)) 동일
x=np.array([1,2,3]) #1d->2d으로 확장해야함
y=np.array([10,20,30])

print(np.column_stack((x,y)))
print(np.column_stack((x[:,np.newaxis],y[:,np.newaxis]))) #?

[[ 1 10]
 [ 2 20]
 [ 3 30]]
[[ 1 10]
 [ 2 20]
 [ 3 30]]


In [ ]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
#np.column_stack((a,b))
#2차원
np.column_stack == np.hstack

False

In [ ]:
#numpy.row_stack -> vstack() 과 결과가 동일
#deprecated :향후 없어질 함수

a=np.arange(6).reshape(2,3)
a
b=np.arange(10,22).reshape(4,3)

np.row_stack((a,b))

/tmp/ipykernel_21291/3781282827.py:8: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
#np.concatenate((a,b),axis=None|0|1) 기본 축 0을 중심으로 합침, 결합한느 축 수정가능
#1d:
#h방향 결합
a=np.array([1,2])
b=np.array([3,4])
c=np.array([5,6])

np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [ ]:
# np.concatenate((a,b,c),axis=1) #AxisError: axis 1 is out of bounds for array of dimension 1
#1차원은 축0만 존재

In [ ]:
#numpy.concatenate 2dimentsion

x=np.arange(6).reshape(2,3)
y=np.arange(10,16).reshape(2,3)

z=np.arange(20,24).reshape(2,2)

#np.concatenate((x,y))

In [ ]:
np.concatenate((x,y))
#vstack() && row_stack() 동일

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate((x,y),axis=1)
#hstack() && column_stack() 동일

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate((x,y),axis=None) #?? 0axis아닌가?

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
#np.stack()

a=np.array([1,2,3])
b=np.array([4,5,6])
np.stack((a,b))



array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a,b),axis=0)
np.stack((a,b),axis=-1) #마지막 차원 ,axis=-1


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#3차원 배열 이해
#shape(3,3,3) => 3행 3열의 2차원 배열이 3개 모임

In [ ]:
c=np.arange(1,19).reshape(3,3,2)
c
#axis=0은 전체 , axis=1은 각 행렬의 열 , axis=2는 행

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
np.size(c)
np.ndim(c)
#np.dtype(c)

TypeError: Cannot construct a dtype from an array

In [ ]:
#np.stack()

x=np.arange(6).reshape(2,3)
y=np.arange(10,16).reshape(2,3)
z=np.arange(20,26).reshape(2,3)

ax0=np.stack((x,y,z),axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [ ]:
ax0.shape #2row 3col , 3개

(3, 2, 3)

In [ ]:
ax0=np.stack((x,y,z),axis=1)
ax0

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [ ]:
ax0=np.stack((x,y,z),axis=2)
ax0

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
#np.stack((),axis=2)
x[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
np.expand_dims(y,axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
#np.stack()

np.expand_dims(x,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

## 수업

In [ ]:
#수업
import numpy as np
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c=np.arange(1,6,2)
c

array([1, 3, 5])

In [ ]:
np.hstack((a,np.expand_dims(c,axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
#row_stack() & vstack()

In [ ]:
#@@@ np.c_[] 함수가 아니라 함수 비슷한 역할, 대골호 인데스
#대괄호 사용해야함
a=np.array([1,2,3])
b=np.array([4,5,6])

result=np.c_[a,b]
result

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#same as ㅎㅎ
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#???, 시험에는 안넣음,
np.r_['-1,2,0',a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
array([[4,5,6]])

NameError: name 'array' is not defined

In [ ]:
#2차원 np.c_[] and np.column_stack() 27p.
x=np.array([[1,2,3]])
y=np.array([[4,5,6]]) # np.array([1,2,3])vs np.array([[1,2,3]]) 차이는?

np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
x.shape,y.shape

((1, 3), (1, 3))

In [ ]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
#np.c_[] ,함수는 아닌 대괄호 인덱스 []사용으로 배열 객체 반환
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
#np.r_[] rody, 수평으로 또는수직으로도  합칠 수 있는 다양한 결합 방식을 제공
#다양한 결합 가능, 1차원 벡터들을 나열(1차원 나열로 결합)
# i: 결합 (쌓는 )하는 축(axis) , np.r['0',a,a] 배열 a 2개를 첫 축인 0으로 결합
#이것저것 많이 하는 수평 수직 쌓기 가능,
a=np.array([[1,2,3],[4,5,6]])
a=np.arange(1,7).reshape(2,3)
a
np.r_[a,a,a]

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_['0',a,a] #concatenate along의 first axis??

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_['-1',a,a] # 배열 a 2개를 마지막 축인 축 1로 결합

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
np.r_['1',a,a] # concatenae the last axis # 차이 column_stack() 차이?

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#np.r_[]개요, 수평이로 또는 수직으로 합칠 수 있는 다양한 결합 방법을 제공
#28p
a=np.array([2,3,4])
b=np.array([4,5,6])
np.r_[a,b]

array([2, 3, 4, 4, 5, 6])

In [ ]:
np.hstack((a,b))

array([2, 3, 4, 4, 5, 6])

In [ ]:
np.row_stack((a,b))

/tmp/ipykernel_686/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[2, 3, 4],
       [4, 5, 6]])

In [ ]:
#29p
np.r_[a,0,0,0,b]

array([2, 3, 4, 0, 0, 0, 4, 5, 6])

In [ ]:
np.r_[3:10:3,[0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [ ]:
np.r_[-1:1:6j,[0]*2,5,6]
#간격 : ((1-(-1)/5)=0.4)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [ ]:
#30ㅔ
#np.r['i',a,b]
a=np.array([[0,1,2],[3,4,5]])
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

## 4.2 배열 분리

In [ ]:
#split(ary,indices_or_sections,axis=0)
#배열 ary를 축따라 indices_or_sections로 분할해 배열의 목록을 반환

In [2]:
#np.vsplit(),np.hsplit()
import numpy as np
ex=np.arange(18).reshape(3,6)


In [3]:
ex

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [4]:
np.split(ex,3,axis=0)
#np.vsplit(x,3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [5]:

np.split(x,(1,2),axis=0)

NameError: name 'x' is not defined

In [6]:
#50p
import numpy as np
x=np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [7]:
s=np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [9]:
#np.split
import numpy as np

y=np.arange(10,61,10)
np.split(y,[2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [10]:
np.split(x,[2,6])
#[2,6]인덱스 2에서 6까지 한 덩어리가 가운데 들어감

[array([0., 1.]), array([2., 3., 4., 5.]), array([6., 7., 8.])]

In [13]:
a=np.arange(24).reshape(2,12)
print(a)
np.split(a,3,axis=1)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [12]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
np.split(a,4,axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
#다차원 배열 np.split(ary,axis=1)
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
#np.split : 다차원 배열 np.split(ary,n,axis=0)
b=np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.split(b,[2,4,6],axis=0)
#위에건 3개로 나눈는데이건 뭐지?

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [20]:
a=np.arange(24).reshape(2,12)
print(a)


[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [19]:
np.split(a,[3,5,7],axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [21]:
b=np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [26]:
#np.hsplit(ary,n)
#1차원은 잘라도 동일하게 1차원 나옴 55p
a=np.arange(10)
np.hsplit(a,2)


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [24]:
np.hsplit(a,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [27]:
#np.hsplit
a=np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [28]:
np.hsplit(a,(3,5,8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [29]:
a[:,:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [30]:
a[:,8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [31]:
#np.vsplit(a,n)
a=np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [32]:
np.vsplit(a,3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [34]:
#58P , 오타 첨자 (1,4,6)
#np.vsplit(a,[i,j,k])
a=np.arange(18).reshape(6,3)
np.vsplit(a,(1,4,6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [47]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [36]:
a[:1,:]

array([[0, 1, 2]])

In [37]:
a[4:6,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [38]:
a[6:,:]
#5줄 마지막 줄이 인덱스 6이긴함
#마지막 6으로 시작하는 배열은 원소가 없는 배열

array([], shape=(0, 3), dtype=int64)

In [39]:
#3차원 배열의 vsplit(a,n)

x=np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [49]:

np.split(x,2,axis=2)

[array([[[ 0],
         [ 2],
         [ 4],
         [ 6]],
 
        [[ 8],
         [10],
         [12],
         [14]],
 
        [[16],
         [18],
         [20],
         [22]],
 
        [[24],
         [26],
         [28],
         [30]]]),
 array([[[ 1],
         [ 3],
         [ 5],
         [ 7]],
 
        [[ 9],
         [11],
         [13],
         [15]],
 
        [[17],
         [19],
         [21],
         [23]],
 
        [[25],
         [27],
         [29],
         [31]]])]

In [41]:
np.vsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [42]:
#60p, 3차원 배열의 vsplit(a,[i,j...])
x=np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.vsplit(x,[1,3]) #은 np.split(x,2,axis=0)과 동일

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [ ]:
x[:1,:,:]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [ ]:
x[1:3,:,:]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
x[3,:,:]

array([[24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [ ]:
#3차원 배열의 hsplit(a,n)
#61p, 3차원 이상의 hsplit에서는 두번째축인 axis=1로 n등분 분할
x=np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [43]:
np.hsplit(x,2)
 # hsplit 으로 전에는 (4,4,2) 를 (4,2,4) 두개로
 #np.split(a,axis=1)동일

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [44]:
#same as upper one
np.split(x,2,axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [45]:
#3차원 배열의 hsplit(a,[i,j,k])
x=np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [46]:
np.hsplit(x,[1,3]) #분리는 :1 1:3 3:  3개로 분리

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

In [ ]:
print((np.hsplit(x,[1,3]).type)

SyntaxError: incomplete input (3803817547.py, line 1)

## 4.3 numpy 난수 and 다양한 함수

In [ ]:
#난수 기초
# numpy.Random.default_rng
#난수를 만드는 생성기(generator) 의 생성자(constructor)
# 다음 코드로 실수 난수를만드는 제너레이터를 생성
#인자 12345는 비트제너레이터를 초기화하는 시드 값, 시드 값일 같으면 호출 순서에 따라 난수가 발생하는 값이 동일

In [ ]:
import numpy as np
rg=np.random.default_rng(12345)
rg.random() # result : 0.22733602246716966 be) same seed 값 때문이다
# [0:1) 0포함 , 1 포함 x

0.22733602246716966

In [ ]:
#난수 제너레이터 함수 random()
r=rg.random()
r

0.33281392786638453

In [ ]:
rg.random(5) #5개 요소가 있는 배열을 만든다

array([0.59830875, 0.18673419, 0.67275604, 0.94180287, 0.24824571])

In [ ]:
rg.random((4,3)) #2dim

array([[0.94888115, 0.66723745, 0.09589794],
       [0.44183967, 0.88647992, 0.6974535 ],
       [0.32647286, 0.73392816, 0.22013496],
       [0.08159457, 0.1598956 , 0.34010018]])

In [ ]:
rg.random((4,3,2)) #3dim

array([[[0.46519315, 0.26642103],
        [0.8157764 , 0.19329439],
        [0.12946908, 0.09166475]],

       [[0.59856801, 0.8547419 ],
        [0.60162124, 0.93198836],
        [0.72478136, 0.86055132]],

       [[0.9293378 , 0.54618601],
        [0.93767296, 0.49498794],
        [0.27377318, 0.45177871]],

       [[0.66503892, 0.33089093],
        [0.90345401, 0.25707418],
        [0.33982834, 0.2588534 ]]])

In [ ]:
rg.random((4,3)) #2dim

array([[0.94888115, 0.66723745, 0.09589794],
       [0.44183967, 0.88647992, 0.6974535 ],
       [0.32647286, 0.73392816, 0.22013496],
       [0.08159457, 0.1598956 , 0.34010018]])

In [ ]:
#난수 제너레이터 함수 integers() 75p
rg=np.random.default_rng(12345)
r=rg.integers(low=0.,high=10,size=3) #low 최솟값, high값은 , 3은size
r


array([6, 2, 7])

In [ ]:
rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [ ]:
rg=np.random.default_rng(12345)
r=rg.integers(low=0.,high=20,size=(3,4)) #low 최솟값, high값은 , 3은size
r

array([[13,  4, 15,  6],
       [ 4, 15, 12, 13],
       [19,  7, 16,  6]])

In [ ]:
rg.integers(1,7,[3,4])

array([[4, 4, 2, 2],
       [2, 5, 4, 6],
       [5, 2, 6, 6]])

In [ ]:
#난수 생성자 함수 standard_normal()
#정규분포 ,실수,표준 정규분포 68,95,99.7
rg=np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [ ]:
rg.standard_normal((3,4))
#실수도 나오고 ,음수도 나오고, 1을 넘는것도 있고(), 2넘는거 적음, 3거의 없음,4는 없다고 봐도 ,,,

array([[ 1.72366572, -0.17951921, -0.38318732,  1.46144429],
       [-1.10704568, -0.89472702,  0.64332679, -0.39460512],
       [-0.00512187, -0.1634429 ,  0.33757455,  1.40748186]])

#표준 정규 분포
- 평균=0이다
- 0=u, u+a=1, u+2a=2,u+3a=3
- u-a=-1, u-2a=-2, u-3a=-3
- 68%= (u-a:u+a)
- 95% = (u-2a:u+2a)
- 99.7% = (u-3a:u+3a)
- 68, 95 , 99.7 @@@

In [ ]:
rg.standard_normal(500)

array([ 9.05849069e-02,  6.43938793e-01, -2.05017210e+00, -4.87184019e-02,
       -8.43230270e-01, -1.21881306e+00, -8.78152367e-01, -3.34123441e-01,
        9.15902542e-01, -1.32639272e+00,  3.06314926e-02, -4.84169433e-01,
       -3.27673094e-01,  1.00275783e+00,  5.38115437e-01,  1.33739811e+00,
       -1.54505679e-01, -6.95942612e-01, -2.23858817e-01,  2.42496791e-01,
        1.76573358e-01, -1.08438807e+00,  9.04897816e-02,  2.28228330e-01,
        2.51747404e+00,  1.87684461e+00, -8.53243351e-01, -2.87383362e-01,
       -1.46344200e+00, -5.90707014e-01,  3.15605004e-01,  1.20585362e+00,
       -7.29083838e-01, -6.54146440e-01, -2.14728903e+00, -1.62665921e-01,
       -1.06241441e+00, -5.29439427e-01, -8.76860778e-01, -9.42625543e-02,
       -1.75772839e+00, -1.46704525e+00,  2.12924711e+00, -1.28742258e+00,
       -1.09678558e+00,  1.83691353e+00,  2.90506717e+00, -1.17156663e+00,
       -3.68248957e-01,  3.41555551e-01,  1.72869764e+00, -9.86857078e-01,
       -2.45277846e-01,  

## 배열 결합 연습

In [ ]:
#연습  ,1차원
a=np.arange(1,4)
b=np.arange(4,7)
c=np.arange(7,10)
a,b,c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
#연습 ,2차원
p=np.arange(1,7).reshape(2,3)
q=np.arange(11,17).reshape(2,3)
r=np.arange(21,27).reshape(2,3)
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.vstack((a,b,c)) #1d 2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack((p,q,r)) #2d 2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.hstack((p,q,r)) #2d -> 2d

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
a,b,c #1d

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
np.column_stack((a,b,c)) #1d -> 2d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((a,b,c)) #1d 1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#np.concatenate((a,b,c),axis=1) #1d 1d
 #error ) AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.concatenate((a,b,c),axis=None) #1d 1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a,b,c),axis=-1) #1d 1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((p,q,r),axis=-1) #2d 2d

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((p,q,r),axis=None) #2d 2d

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [ ]:
np.c_[a,b,c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.c_[(a,b,c)]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((a,b,c)) #인덱서가 아니라서 대괄호 아닌 소괄호 , tuple 사용

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.c_[p,q,r] #2d 2d

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.r_[p,q,r] #2d 2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.r_[a,b,c] #1d 1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.vstack((p,q,r)) #2d 2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
#중간 제외
#np.r_['i,j',a,b]
