<a href="https://colab.research.google.com/github/dwelle511/2026BDA/blob/main/BDA_Day03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy 다차원 배열
#nd= multi dimension,동일한 크기 자료형 항목 자료형 으로 구성, numpy.ndarray(size,dtype)

import numpy as np

a=np.ndarray((2,3))
a

array([[ 4.72700825e-315,  0.00000000e+000,  9.74360573e-305],
       [ 6.83149322e-117, -4.20453507e+078,  1.52675306e-307]])

In [2]:
a=np.ndarray((3,2),dytpe=int)
a

TypeError: 'dytpe' is an invalid keyword argument for ndarray()

In [ ]:
#기본 자료형 @@@@
#bool, int, float, complex,int8,int16,int32, uint8=부호 없는 8bit정수 , float16=16bit 부동 소수점
#complex128= 128bit 복소수
#
#@@@@
#ndarray.shape= 배열의 차원을 나타내는 튜플, 각 차언의 크기 표현
#.ndim= array 차원 수 , .size=array 요소 수
#.dtype=array 데이터 형식, .itemsize=array 각 요소의 크기(byte), nbytes=array 전체 크기(byte)
#ndarray.data= array 요소를 실제로 표함하고 있는 버퍼의 시작 위치

In [ ]:
#내장 함수 array()


#1차원 (3,) 로 나옴
#

In [ ]:
#ndarray 특징, 하나라도 문자열이면 모든 항목이 동일하게 유니코드 문자열 자료형인 '<u32'지정


## 내장함수 arange() linspace()

In [7]:
#numpy.arange()

import numpy as np
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(1,7,2.3))
#py, range(){{정수}}만됨 vs numpy arange()는 '실수'도된

[0 1 2]
[3 4 5 6]
[1.  3.3 5.6]


In [8]:
import numpy as np
print(np.arange(3.0))
print(np.arange(3.3,7.4))
print(np.arange(1.0,7.0,2.3))

[0. 1. 2.]
[3.3 4.3 5.3 6.3 7.3]
[1.  3.3 5.6]


In [9]:
#reshape() 배열의 모양을 바꾸는
#

import numpy as np

a=np.arange(12).reshape(3,4) #.reshape(n,m) 2개라 2차원
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.reshape(a,(2,6)) #12개

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
np.reshape(a,(3,5)) #size원소 개수 다름, 15개

ValueError: cannot reshape array of size 12 into shape (3,5)

In [14]:
#linspace(start,stop,num) @@
#일정한 간격의 값으로 배열 생성
#동일한 길이의 하위 간격으로 분할하는 수가 나열된 1차원 배열을 반환
#arrays with regularly-spaced
#전체 구간은 [시작, 끝]으로 기본적인 양쪽을 모두 포함, 일정한 간격을 구성하는 값인 배열의 수를 매개변수 num에 지정하여 기본값은 50
#np.linspace(start,stop,num) #num부분에 이제 step=2 즉 원소개수 2개라는거다
linsp=np.linspace(0,10,2)
linsp

array([ 0., 10.])

In [17]:
#start=포함, stop=포함, num=성성 점의 개수=step=(stop-start)/(num-1)\
stepNum=(10-0)/(2-1)
print("num구간의 개수아닌 크기",stepNum)

#np.arange= step크기 지정 vs np.linspace=점 개수 지정, 구간 정확힌 n등분시 유리함

num구간의 개수아닌 크기 10.0


In [ ]:
#linspace(start,stop,num)
#numpy.linspace(start,stop,num=50,endpoint=True,restep=False,dtype=None,axis=0)

#지정된 간격에 걸쳐 균등한 간격의 숫자를 반환
#endpoint: bool,optional, 끝점은 제외 될 수 있음=True, False=제외
# retstop=True: (samples,step)반환= step 샘풀 수 사이 간격= step크기, false=samples만 반환

In [18]:
#지정된 간격에 걸쳐 균등한
#89P.
np.linspace(2.0,3.0) #50개 자동

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [19]:
np.linspace(2.0,3.0,retstep=True) #
#바닥에 무엇?

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [20]:
#step size
print((3-2)/(50-1))

0.02040816326530612


In [22]:
np.linspace(2.0,3.0,3,endpoint=False,retstep=True) #끝수 포함 제외


(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [23]:
np.linspace(2.0,3.0,3,endpoint=True,retstep=True) #끝수 포함


(array([2. , 2.5, 3. ]), np.float64(0.5))

In [25]:
np.linspace(2,3,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

#3.3 내장 함수 zeros() ,ones(),empty()

In [27]:
#내장함수 np.zeros()
#주어지는 shape형태로 0.0이 채워진

import numpy as np
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [30]:
b=np.zeros((2,1)) #.zeros((행개수, 열))
b

array([[0.],
       [0.]])

In [31]:
b=np.zeros((2,3)) #.zeros((행개수, 열))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#원소가 모두 1.0인 배열을 생성 .one()
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.ones((2,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
#numpy.eye() 대각선 원소가 모두 1인 2차원 배열을 반환하는 함수
#대각행렬 만들때, eye(m,n,k),m row, n col, k=+n으로 양수, k=-n음수

np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
#numpy.full
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [39]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
np.full([2,3],(1,2)) #error =>

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [42]:
#np.full

np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [47]:
np.arange(4).reshape(4,1) #이거인데 full(row, col)로 오른쪽 으로 복사한게 다음 거

array([[0],
       [1],
       [2],
       [3]])

In [46]:
#원래 arange하면 1차원 배열 생성, reshape(row,col) 4row,1col생성
np.full([4,3],fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [48]:
#지정한 모양의 배열을 생성하는 numpy.empty(shape)
#같은 메모리 값 지정
# 원소 값 예측 할 수 없음
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [52]:
np.empty([2,2])

TypeError: 'list' object is not callable

## 3.4 배열 연산

In [68]:
#2차원 배열이 곱 연산자 = @
#(3,2) @(2,1)
x=np.arange(1,7).reshape(2,3)
x
y=np.arange(1,3).reshape(1,2)
y
print(x @ y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [69]:
#배열 함수 @@
a=np.array([[10,20],[5,7],[1,2]])
a

array([[10, 20],
       [ 5,  7],
       [ 1,  2]])

In [71]:
a.sum()

np.int64(45)

In [72]:
a.sum(axis=1)

array([30, 12,  3])

In [74]:
import numpy as np
 #@@@@
print(np.sum(a))
print(np.sum(a,axis=0)) #열 더한거
print(np.sum(a,axis=1)) # 행으로 더한거


45
[16 29]
[30 12  3]


In [79]:
#배열 함수 a.cumsum()

a=np.array([[3,5,8],[1,2,3]])
a
a.cumsum()
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

## 3.5배열 슬라이싱과 형태 수정 @@@@

In [81]:
#1차원 배열의 첨자와 슬라이싱
#a[i] 첨자, a[m:n] , a[m:n:s]
import numpy as np
a=np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [88]:
print(a[3])
print(a[-1])
print(a[1:4])
print(a[-5:-1])
print(a[8:2:-1])
print(a[-1:-7:-1])

9
81
[1 4 9]
[25 36 49 64]
[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [92]:
#역순 대입
a[::-2]


array([81, 49, 25,  9,  1])

In [94]:
#2차원 배열 첨자와슬라이싱
#행 잠조 x[row] x[row,] x[row,:]

a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [100]:
#@@@
print(a[-2:])

[[18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [105]:
#2차원 배열의 첨자와 슬라이싱
#행반환 : x[row],x[row],x[row,:]
#열반환 : x[:,col] ,error ) x[,col] :콜른 넣기!
#원소 반환 : x[row,col]

a=np.arange(30).reshape(5,6)
a[:,1:3]


array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26]])

In [109]:
#2차원 배열 첨자와 슬라이싱
a[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [113]:
#3차원 배열 , (3,3,3) 3행 3열의 2차원 배열 3개 / (3,) (3,3) (3,3,3)
#3차원 배열 (2,3,4) 3행 4열인 2차원 배열 2개로
a=np.arange(72).reshape(6,3,4) #@@@
a


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71]]])

In [ ]:
#3개축 0축 =(나,etc,etc) 나[0]번째 덩어리임 1축 =각 행  2축=각 열

In [ ]:
#3차원 배열의 다양한 참조
# a[1] axis=0 첨자 1
# a[:,1] axis=0
#a[:,1,1] axis=0인 모든 배열, 위치 (1,1)
# a[:,:,1]
#a[...1] 해당되는 축이 모두:것을 의미= 동일함 a[:,:,1]
#a[1,...,1] axis=0의 첨자 1 , axis=2의 첨자 1인 (3,)모양 1차원 배열이 반환
#a[0,...]

In [141]:
#@@@@

a=np.arange(24).reshape(2,3,4) #@@@
a[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
#1차원 배열로 만드는 ndarray.ravel()
#행렬인 a에서 a.ravel()의 반환 값은 (a.size,)모양의 1차원 배열
a=np.arange(12).reshape(2,3,2)
a
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
#np.transpose(a) a.transpose(),aT @@@ 함수 호출, 전치 행렬, 행과 열이 바뀜,(2,3)->(3,2)
#2차원 a.T는 쉬운데 3차원은 복잡
a=np.arange(1,7).reshape(2,3)
print(a)


print(np.transpose(a))

NameError: name 'br' is not defined

In [ ]:
#3차원 배열 전치행렬 , (3,2,2)-> (2,2,3) ex(i,j,k)->(l,j.i) j는 위치가 그대로
# 전치 행렬 방법 6갸 존쟈 ㅋㅋㅋㅋㅋ, #49~59페이지 시험 제외

## 3.6 브로드캐스팅

In [53]:
#broadcasting: 산술 연산 ㅅ ,
a=np.array([3,4,5])
b=np.array([8,7,6])
a+b

array([11, 11, 11])

In [54]:
a=np.array([3,4,5])
b=np.array([8,7,6,6]) #error => operands could not be broadcast together with shapes (3,) (4,)
#두 배열 크기 달라 안됨
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [56]:
#하나의 배열 이 1차원으로 다른 배열 열수 와 같은 구조의 브로드캐스팅

#(3,3)*(3,) or (1,3) 아래로 확장
#
from numpy import  arange
x=arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
y=arange(-1,2) #linspace 50=num
y

array([-1,  0,  1])

In [58]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [59]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [157]:
#하나의 배열이 2차원으로 다른 배열 행수와 같은 구조의 브로드 캐스팅
#row-wise, normalization
from numpy import arange
x=arange(1,10).reshape(3,3)

y=arange(3,10,3).reshape(3,1)

np.set_printoptions(precision=2) #소수점 이하 자릿수를 2자리로 설정,2차원 배열

print(x)
print(y)
print(x/y)
print(x-y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]
[[0.33 0.67 1.  ]
 [0.67 0.83 1.  ]
 [0.78 0.89 1.  ]]
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


In [ ]:
#행 또는 열이 1인 두 배열의 브로드 캐스팅


In [158]:
#상수 np.newaxis 활용한 배열 차원의 확장 =증가, 배열 x:(4,)인 1차원 배열
#x[None,:]또는 x[np.newaxis:], none 이 있는 축인 행이 추가, 모양 (1,4)의 2차원 배열의 보기 (view)
#가 반환, 즉 1차원에서 행이 추가디어 2차원으로 차원 증가
a=x[None,:]
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [159]:
#연산 a+b수행, 배열 a는 열이 1이며 배열 b는 행이 1
a=x[:,np.newaxis]
a

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

## 3.7 고급 색인

In [160]:
#1차원 배열 색인, 1차원 배열 x, x[i] 첨자 i인 원소 참조, 시퀸스인 첨자라면 여러 언소로 구성된 배열 반환
#x[[i,j,k,...]]: 정수 배열 or list 인텍싱, 배열에서 여러 첨자인 원소 선택, 정수 배열 또느 리스트 반환값도 배열
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
print(x[1])
print(x[:5])
print(x[[2]])
print(x[[2,3]]) #결과는 1차원 배열
print(x[[2,3,5,8]]) #결과는 1차원 배열
x[np.array(5,3,-4,8)] #결과는 1차원 배열

1
[0 1 2 3 4]
[2]
[2 3]
[2 3 5 8]


TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [171]:
x=np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [172]:
int(x[0,1])

1

In [173]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [174]:
x[,2:8] #:콜론 뺌면 안됨, 3차원이면 가능하지 않나

SyntaxError: invalid syntax (1821174162.py, line 1)

In [179]:
x[...,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [180]:
x[0,1]

np.int64(1)

In [181]:
x[[0],[1]] #위에 거랑 다른데 어래이이다,행축 열축 해당하는 배열을 만든것

array([1])

In [187]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [182]:
x[[0,1]] #행번호의 모임

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [183]:
x[[1,3,5]]
#x[[1,3,5],:]
#행번호의 모임 => 고급 색인, 안에 리스트형시그올 써서
#

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [188]:
x[[1,3],[2,2]]

array([10, 26])

In [189]:
x[[1,3],[2]]

array([10, 26])

In [191]:
#행과 열 참조 매핑
#x[[0,2,4],[1]]
x[[0,2,4],1]

array([ 1, 17, 33])

In [193]:
#슬라이싱
x[[0,2,4],:1]

array([[ 0],
       [16],
       [32]])

In [194]:
#기본 색인
from numpy import arange
a=arange(40).reshape(5,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [195]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [196]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [197]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [198]:
#고급 색인 방법
from numpy import arange
a=arange(40).reshape(5,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [199]:
a[arange(2,4)][:,[1,0]] #

array([[17, 16],
       [25, 24]])

In [204]:
a[arange(2,4)][:,[1,1,0]] #

array([[17, 17, 16],
       [25, 25, 24]])

In [200]:
a[arange(2,5)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [201]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [202]:
a[arange(2,5)][:,arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [206]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [207]:
a[[2,3,4]][:,[-1,-2,-3,-4,-5,-6,-7]]


array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [209]:
a[np.arange(2,5)][np.arange(-1,-8)]

array([], shape=(0, 8), dtype=int64)

In [210]:
a[np.arange(2,5)][:,np.arange(-1,-8,-1)] #위에거가 안된=ㅁ

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])